### ISSUE TITLE
[Вопрос] Уровень татарского проекта.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [xi816/Ochpochmak#4]
Исәнмесез!

Хочу узнать, насколько серьёзно здесь следует относиться к "татарскому"? Имею под этим то, что это должен быть забавный (то есть, с ошибками и прочими элементами язык) или действительный перевод?

**Comment by xi816** [comment]
Не прямо действительный уж. Где-то посередине

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Не прямо действительный уж. Где-то посередине

Тогда забаву с "сортировать итәбез" проигнорирую, потому что это просто смешно и, в этом случае, по-хорошему глупо =)... но вот от "исемләр" немного корёжит (если слово на -м, -н или на -ң, то не -лар/-ләр, а -нар/-нәр => "исемнәр")

Ну, и ещё хотелось бы попросить где-то отметить этот момент (насколько здесь серьёзный уровень татарского)... пусть даже через описание.
